server:
  PortServer: :5000

secret:
  JwtSecretKey: secretkey

mysql:
  MysqlHost:     localhost
  MysqlPort:     3306
  MysqlUser:     root
  MysqlPassword: 1234
  MysqlDbname:   db
  MysqlDriver:   mysql

postgres:
  PostgresqlHost: john.db.elephantsql.com
  PostgresqlPort: 5432
  PostgresqlUser: fpdlysgd
  PostgresqlPassword: TBX6DJGFGz-GHSPLXSP0764JvnPl886R
  PostgresqlDbname: fpdlysgd
  PgDriver: pgx